# Python
from threading import Thread

# External
from numpy import uint8

# Local
from .exceptions import UnhandledInstructionError
from .flags import Flag
import instructions as instr
from .registers import Register

class CPU(Thread):
    def __init__(self, *args, **kwargs):
        Thread.__init__(self, *args, **kwargs)
        self._registers = {
            'a': Register(uint8), 
            'b': Register(uint8), 
            'c': Register(uint8), 
            'd': Register(uint8), 
            'e': Register(uint8), 
            'h': Register(uint8), 
            'l': Register(uint8)
        }

        self._flags = {
            's': Flag(uint8), 
            'z': Flag(uint8), 
            'p': Flag(uint8), 
            'c': Flag(uint8), 
            'ac': Flag(uint8), 
            'pad': Flag(uint8)
        }

        self._sp = Register(uint8)
        self._pc = Register(uint8)

        self._instructions = {
            0x00: instr.NOPInstruction(self), 
            0x01: instr.LXIInstruction(self), 
            0x02: instr.STAXInstruction(self), 
            0x03: instr.INXInstruction(self), 
            0x04: instr.INRInstruction(self), 
            0x05: instr.DCRInstruction(self), 
            0x06: instr.MVIInstruction(self), 
            0x07: instr.RLCInstruction(self), 
            0x08: instr.NOPInstruction(self), 
            0x09: instr.DADInstruction(self), 
            0x0a: instr.LDAXInstruction(self), 
            0x0b: instr.DCXInstruction(self), 
            0x0c: instr.INRInstruction(self), 
            0x0d: instr.DCRInstruction(self), 
            0x0e: instr.MVIInstruction(self), 
            0x0f: instr.RRCInstruction(self), 

            0x10: instr.NOPInstruction(self), 
            0x11: instr.LXIInstruction(self), 
            0x12: instr.STAXInstruction(self), 
            0x13: instr.INXInstruction(self), 
            0x14: instr.INRInstruction(self), 
            0x15: instr.DCRInstruction(self), 
            0x16: instr.MVIInstruction(self), 
            0x17: raise UnhandledInstructionError(), 
            0x18: instr.NOPInstruction(self), 
            0x19: instr.DADInstruction(self), 
            0x1a: instr.LDAXInstruction(self), 
            0x1b: instr.DCXInstruction(self), 
            0x1c: instr.INRInstruction(self), 
            0x1d: instr.DCRInstruction(self), 
            0x1e: instr.MVIInstruction(self), 
            0x1f: raise UnhandledInstructionError(), 

            0x20: instr.NOPInstruction(self), 
            0x21: instr.LXIInstruction(self), 
            0x22: raise UnhandledInstructionError(), 
            0x23: instr.INXInstruction(self), 
            0x24: instr.INRInstruction(self), 
            0x25: instr.DCRInstruction(self), 
            0x26: instr.MVIInstruction(self), 
            0x27: raise UnhandledInstructionError(), 
            0x28: instr.NOPInstruction(self), 
            0x29: instr.DADInstruction(self), 
            0x2a: raise UnhandledInstructionError(), 
            0x2b: instr.DCXInstruction(self), 
            0x2c: raise INRInstruction(self), 
            0x2d: instr.DCRInstruction(self), 
            0x2e: instr.MVIInstruction(self), 
            0x2f: raise UnhandledInstructionError(), 

            0x30: instr.NOPInstruction(self), 
            0x31: instr.LXIInstruction(self), 
            0x32: raise UnhandledInstructionError(), 
            0x33: instr.INXInstruction(self), 
            0x34: instr.INRInstruction(self), 
            0x35: instr.DCRInstruction(self), 
            0x36: instr.MVIInstruction(self), 
            0x37: raise UnhandledInstructionError(), 
            0x38: instr.NOPInstruction(self), 
            0x39: instr.DADInstruction(self), 
            0x3a: raise UnhandledInstructionError(), 
            0x3b: instr.DCXInstruction(self), 
            0x3c: instr.INRInstruction(self), 
            0x3d: instr.DCRInstruction(self), 
            0x3e: instr.MVIInstruction(self), 
            0x3f: raise UnhandledInstructionError(), 

            0x40: raise UnhandledInstructionError(), 
            0x41: raise UnhandledInstructionError(), 
            0x42: raise UnhandledInstructionError(), 
            0x43: raise UnhandledInstructionError(), 
            0x44: raise UnhandledInstructionError(), 
            0x45: raise UnhandledInstructionError(), 
            0x46: raise UnhandledInstructionError(), 
            0x47: raise UnhandledInstructionError(), 
            0x48: raise UnhandledInstructionError(), 
            0x49: raise UnhandledInstructionError(), 
            0x4a: raise UnhandledInstructionError(), 
            0x4b: raise UnhandledInstructionError(), 
            0x4c: raise UnhandledInstructionError(), 
            0x4d: raise UnhandledInstructionError(), 
            0x4e: raise UnhandledInstructionError(), 
            0x4f: raise UnhandledInstructionError(), 

            0x50: raise UnhandledInstructionError(), 
            0x51: raise UnhandledInstructionError(), 
            0x52: raise UnhandledInstructionError(), 
            0x53: raise UnhandledInstructionError(), 
            0x54: raise UnhandledInstructionError(), 
            0x55: raise UnhandledInstructionError(), 
            0x56: raise UnhandledInstructionError(), 
            0x57: raise UnhandledInstructionError(), 
            0x58: raise UnhandledInstructionError(), 
            0x59: raise UnhandledInstructionError(), 
            0x5a: raise UnhandledInstructionError(), 
            0x5b: raise UnhandledInstructionError(), 
            0x5c: raise UnhandledInstructionError(), 
            0x5d: raise UnhandledInstructionError(), 
            0x5e: raise UnhandledInstructionError(), 
            0x5f: raise UnhandledInstructionError(), 

            0x60: raise UnhandledInstructionError(), 
            0x61: raise UnhandledInstructionError(), 
            0x62: raise UnhandledInstructionError(), 
            0x63: raise UnhandledInstructionError(), 
            0x64: raise UnhandledInstructionError(), 
            0x65: raise UnhandledInstructionError(), 
            0x66: raise UnhandledInstructionError(), 
            0x67: raise UnhandledInstructionError(), 
            0x68: raise UnhandledInstructionError(), 
            0x69: raise UnhandledInstructionError(), 
            0x6a: raise UnhandledInstructionError(), 
            0x6b: raise UnhandledInstructionError(), 
            0x6c: raise UnhandledInstructionError(), 
            0x6d: raise UnhandledInstructionError(), 
            0x6e: raise UnhandledInstructionError(), 
            0x6f: raise UnhandledInstructionError(), 

            0x70: raise UnhandledInstructionError(), 
            0x71: raise UnhandledInstructionError(), 
            0x72: raise UnhandledInstructionError(), 
            0x73: raise UnhandledInstructionError(), 
            0x74: raise UnhandledInstructionError(), 
            0x75: raise UnhandledInstructionError(), 
            0x76: raise UnhandledInstructionError(), 
            0x77: raise UnhandledInstructionError(), 
            0x78: raise UnhandledInstructionError(), 
            0x79: raise UnhandledInstructionError(), 
            0x7a: raise UnhandledInstructionError(), 
            0x7b: raise UnhandledInstructionError(), 
            0x7c: raise UnhandledInstructionError(), 
            0x7d: raise UnhandledInstructionError(), 
            0x7e: raise UnhandledInstructionError(), 
            0x7f: raise UnhandledInstructionError(), 

            0x80: raise UnhandledInstructionError(), 
            0x81: raise UnhandledInstructionError(), 
            0x82: raise UnhandledInstructionError(), 
            0x83: raise UnhandledInstructionError(), 
            0x84: raise UnhandledInstructionError(), 
            0x85: raise UnhandledInstructionError(), 
            0x86: raise UnhandledInstructionError(), 
            0x87: raise UnhandledInstructionError(), 
            0x88: raise UnhandledInstructionError(), 
            0x89: raise UnhandledInstructionError(), 
            0x8a: raise UnhandledInstructionError(), 
            0x8b: raise UnhandledInstructionError(), 
            0x8c: raise UnhandledInstructionError(), 
            0x8d: raise UnhandledInstructionError(), 
            0x8e: raise UnhandledInstructionError(), 
            0x8f: raise UnhandledInstructionError(), 

            0x90: raise UnhandledInstructionError(), 
            0x91: raise UnhandledInstructionError(), 
            0x92: raise UnhandledInstructionError(), 
            0x93: raise UnhandledInstructionError(), 
            0x94: raise UnhandledInstructionError(), 
            0x95: raise UnhandledInstructionError(), 
            0x96: raise UnhandledInstructionError(), 
            0x97: raise UnhandledInstructionError(), 
            0x98: raise UnhandledInstructionError(), 
            0x99: raise UnhandledInstructionError(), 
            0x9a: raise UnhandledInstructionError(), 
            0x9b: raise UnhandledInstructionError(), 
            0x9c: raise UnhandledInstructionError(), 
            0x9d: raise UnhandledInstructionError(), 
            0x9e: raise UnhandledInstructionError(), 
            0x9f: raise UnhandledInstructionError(), 

            0xa0: raise UnhandledInstructionError(), 
            0xa1: raise UnhandledInstructionError(), 
            0xa2: raise UnhandledInstructionError(), 
            0xa3: raise UnhandledInstructionError(), 
            0xa4: raise UnhandledInstructionError(), 
            0xa5: raise UnhandledInstructionError(), 
            0xa6: raise UnhandledInstructionError(), 
            0xa7: raise UnhandledInstructionError(), 
            0xa8: raise UnhandledInstructionError(), 
            0xa9: raise UnhandledInstructionError(), 
            0xaa: raise UnhandledInstructionError(), 
            0xab: raise UnhandledInstructionError(), 
            0xac: raise UnhandledInstructionError(), 
            0xad: raise UnhandledInstructionError(), 
            0xae: raise UnhandledInstructionError(), 
            0xaf: raise UnhandledInstructionError(), 

            0xb0: raise UnhandledInstructionError(), 
            0xb1: raise UnhandledInstructionError(), 
            0xb2: raise UnhandledInstructionError(), 
            0xb3: raise UnhandledInstructionError(), 
            0xb4: raise UnhandledInstructionError(), 
            0xb5: raise UnhandledInstructionError(), 
            0xb6: raise UnhandledInstructionError(), 
            0xb7: raise UnhandledInstructionError(), 
            0xb8: raise UnhandledInstructionError(), 
            0xb9: raise UnhandledInstructionError(), 
            0xba: raise UnhandledInstructionError(), 
            0xbb: raise UnhandledInstructionError(), 
            0xbc: raise UnhandledInstructionError(), 
            0xbd: raise UnhandledInstructionError(), 
            0xbe: raise UnhandledInstructionError(), 
            0xbf: raise UnhandledInstructionError(), 

            0xc0: raise UnhandledInstructionError(), 
            0xc1: raise UnhandledInstructionError(), 
            0xc2: raise UnhandledInstructionError(), 
            0xc3: raise UnhandledInstructionError(), 
            0xc4: raise UnhandledInstructionError(), 
            0xc5: raise UnhandledInstructionError(), 
            0xc6: raise UnhandledInstructionError(), 
            0xc7: raise UnhandledInstructionError(), 
            0xc8: raise UnhandledInstructionError(), 
            0xc9: raise UnhandledInstructionError(), 
            0xca: raise UnhandledInstructionError(), 
            0xcb: raise UnhandledInstructionError(), 
            0xcc: raise UnhandledInstructionError(), 
            0xcd: raise UnhandledInstructionError(), 
            0xce: raise UnhandledInstructionError(), 
            0xcf: raise UnhandledInstructionError(), 

            0xd0: raise UnhandledInstructionError(), 
            0xd1: raise UnhandledInstructionError(), 
            0xd2: raise UnhandledInstructionError(), 
            0xd3: raise UnhandledInstructionError(), 
            0xd4: raise UnhandledInstructionError(), 
            0xd5: raise UnhandledInstructionError(), 
            0xd6: raise UnhandledInstructionError(), 
            0xd7: raise UnhandledInstructionError(), 
            0xd8: raise UnhandledInstructionError(), 
            0xd9: raise UnhandledInstructionError(), 
            0xda: raise UnhandledInstructionError(), 
            0xdb: raise UnhandledInstructionError(), 
            0xdc: raise UnhandledInstructionError(), 
            0xdd: raise UnhandledInstructionError(), 
            0xde: raise UnhandledInstructionError(), 
            0xdf: raise UnhandledInstructionError(), 

            0xe0: raise UnhandledInstructionError(), 
            0xe1: raise UnhandledInstructionError(), 
            0xe2: raise UnhandledInstructionError(), 
            0xe3: raise UnhandledInstructionError(), 
            0xe4: raise UnhandledInstructionError(), 
            0xe5: raise UnhandledInstructionError(), 
            0xe6: raise UnhandledInstructionError(), 
            0xe7: raise UnhandledInstructionError(), 
            0xe8: raise UnhandledInstructionError(), 
            0xe9: raise UnhandledInstructionError(), 
            0xea: raise UnhandledInstructionError(), 
            0xeb: raise UnhandledInstructionError(), 
            0xec: raise UnhandledInstructionError(), 
            0xed: raise UnhandledInstructionError(), 
            0xee: raise UnhandledInstructionError(), 
            0xef: raise UnhandledInstructionError(), 

            0xf0: raise UnhandledInstructionError(), 
            0xf1: raise UnhandledInstructionError(), 
            0xf2: raise UnhandledInstructionError(), 
            0xf3: raise UnhandledInstructionError(), 
            0xf4: raise UnhandledInstructionError(), 
            0xf5: raise UnhandledInstructionError(), 
            0xf6: raise UnhandledInstructionError(), 
            0xf7: raise UnhandledInstructionError(), 
            0xf8: raise UnhandledInstructionError(), 
            0xf9: raise UnhandledInstructionError(), 
            0xfa: raise UnhandledInstructionError(), 
            0xfb: raise UnhandledInstructionError(), 
            0xfc: raise UnhandledInstructionError(), 
            0xfd: raise UnhandledInstructionError(), 
            0xfe: raise UnhandledInstructionError(), 
            0xff: raise UnhandledInstructionError() 
        }

    def _write():
        pass

    def run(self):
        print('Running CPU')
